apiVersion: v1
kind: Pod
metadata:
  name: labelexother
  labels:
    env: production
    owner: rnstech
spec:
  containers:
  - name: sise
    image: rnstech/simpleservice
    ports:
    - containerPort: 9876